version: '2'
services:
  app:
    image: projeto:0.0.1
    ports:
      - "8080:8081"
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - rabbitmq # Added dependency on RabbitMQ
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/CasosJudiciais
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      # RabbitMQ Configuration
      - SPRING_RABBITMQ_HOST=rabbitmq # Hostname for RabbitMQ service
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
  db:
    image: 'postgres:16.2'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=CasosJudiciais
    expose:
      - "5432"
  rabbitmq: # New RabbitMQ service
    image: 'rabbitmq:3-management' # Using image with management UI
    container_name: rabbitmq
    ports:
      - "5672:5672" # Standard AMQP port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

